// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW7pLvuFH8LxGvHl_AMq0rmAoCsEDcHAg',
    appId: '1:444459306151:web:fd32e49c66321cad4fdf82',
    messagingSenderId: '444459306151',
    projectId: 'fruitshub-80387',
    authDomain: 'fruitshub-80387.firebaseapp.com',
    storageBucket: 'fruitshub-80387.firebasestorage.app',
    measurementId: 'G-JSCVDR7RV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7TwNQh1vd-GfVHtSxQnxOL-hN6O8il8I',
    appId: '1:444459306151:android:ecde4c1e87c98bea4fdf82',
    messagingSenderId: '444459306151',
    projectId: 'fruitshub-80387',
    storageBucket: 'fruitshub-80387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUXRcgw15IKsszS5IbxwpSozzIdHVbCU',
    appId: '1:444459306151:ios:2ee3476bc28d37c74fdf82',
    messagingSenderId: '444459306151',
    projectId: 'fruitshub-80387',
    storageBucket: 'fruitshub-80387.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUXRcgw15IKsszS5IbxwpSozzIdHVbCU',
    appId: '1:444459306151:ios:2ee3476bc28d37c74fdf82',
    messagingSenderId: '444459306151',
    projectId: 'fruitshub-80387',
    storageBucket: 'fruitshub-80387.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW7pLvuFH8LxGvHl_AMq0rmAoCsEDcHAg',
    appId: '1:444459306151:web:863f9bffcbb0d6994fdf82',
    messagingSenderId: '444459306151',
    projectId: 'fruitshub-80387',
    authDomain: 'fruitshub-80387.firebaseapp.com',
    storageBucket: 'fruitshub-80387.firebasestorage.app',
    measurementId: 'G-T753CS7G7V',
  );
}
